name: Release
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
      && format('Release {0} @ {1} by @{2}', github.ref_name, github.sha, github.actor)
      || '' }}

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  release:
    uses: plusminus-software/plusminus-opensource/.github/workflows/maven-central-release.yml@main
    with:
      java-version: '8'
    secrets: inherit